#!/usr/bin/env python3
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'; SRC=ROOT/'data-src'/'pets-01.json'

def load(p,d): return json.loads(p.read_text(encoding='utf-8')) if p.exists() else d
def write(p,o): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(o,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
def shard(pid):
 s=((pid-1)//500)*500+1; return f'{s:05d}-{s+499:05d}.json'
def codes(t):
 out=[]
 for m in re.findall(r'\b\d{4}(?:\s?\d{2})?(?:\s?\d{3})?(?:\s?\d)?\b',t):
  v=m.replace(' ','')
  if v not in out: out.append(v)
 return out[:8]

def patch_registry():
 attrs=load(DATA/'rules/attributes.json',{'version':1,'definitions':{}}); attrs['version']=max(int(attrs.get('version',1)),8); d=attrs.setdefault('definitions',{})
 d['petNutritionType']={"label":"Фактический вид кормовой продукции","type":"single","options":["Сухой корм","Влажный корм","Лакомство","Кормовая добавка","Иное/не указано"]}
 d['vetDrugRegistered']={"label":"Есть действующее регистрационное удостоверение ветеринарного лекарственного препарата","type":"boolean"}
 d['veterinaryMedicinalClaim']={"label":"Заявлено лечебное/профилактическое ветеринарное действие","type":"boolean"}
 d['liveBiologicalObject']={"label":"Товар содержит живой биологический объект / посадочный материал / икру","type":"boolean"}
 write(DATA/'rules/attributes.json',attrs)
 sources=load(DATA/'sources.json',{'version':1,'sources':{}}); sources['version']=max(int(sources.get('version',1)),6); s=sources.setdefault('sources',{})
 s['cz-pet-feed-scope']={"title":"Какие корма подлежат обязательной маркировке?","authority":"Честный знак / ЦРПТ","url":"https://markirovka.ru/knowledge/tovarnye-gruppy/korma-dlya-zhivotnyh/kakie-korma-podlezhat-obyazatelnoy-markirovke"}
 s['cz-pet-feed-stages']={"title":"Сроки и этапы маркировки кормов для животных","authority":"Честный знак / ЦРПТ","url":"https://markirovka.ru/knowledge/tovarnye-gruppy/korma-dlya-zhivotnyh/sroki-i-etapy-markirovki-kormov-dlya-zhivotnykh"}
 s['pp-rf-674-2024']={"title":"Постановление Правительства РФ от 27.05.2024 № 674","authority":"Официальное опубликование правовых актов","url":"https://publication.pravo.gov.ru/document/0001202405310046"}
 s['cz-vet-drugs-scope']={"title":"Какие ветеринарные препараты подлежат обязательной маркировке?","authority":"Честный знак / ЦРПТ","url":"https://markirovka.ru/knowledge/tovarnye-gruppy/veterinarniye-preparaty/kakie-veterinarnye-preparaty-podlezhat-obyazatelnoy-markirovke"}
 s['cz-vet-drugs-stages']={"title":"Сроки и этапы маркировки ветеринарных препаратов","authority":"Честный знак / ЦРПТ","url":"https://markirovka.ru/knowledge/tovarnye-gruppy/veterinarniye-preparaty/sroki-i-etapy-markirovki-veterinarnykh-preparatov"}
 s['pp-rf-675-2024']={"title":"Постановление Правительства РФ от 27.05.2024 № 675","authority":"Официальное опубликование правовых актов","url":"https://publication.pravo.gov.ru/document/0001202405310045"}
 s['cz-radioelectronics-scope']={"title":"Какие товары подлежат обязательной маркировке? Радиоэлектроника","authority":"Честный знак / ЦРПТ","url":"https://markirovka.ru/knowledge/tovarnye-gruppy/radioelektronika/kakie-tovary-podlezhat-obyazatelnoy-markirovke-radioelektronika"}
 s['cz-radioelectronics-stages']={"title":"Сроки и этапы маркировки радиоэлектронной продукции","authority":"Честный знак / ЦРПТ","url":"https://markirovka.ru/knowledge/tovarnye-gruppy/radioelektronnaya-produktsiya-noutbuki-i-smartfony/sroki-i-etapy-markirovki-noutbuki-i-smartfony"}
 write(DATA/'sources.json',sources)

def marking(cur='no',label=None,experiment='no'):
 return {'current':{'status':cur,'label':label or ('Обязательная маркировка по выявленному сценарию не обнаружена' if cur=='no' else 'Требуется проверка по точному коду')},'future':{'status':'no','label':'Отдельный утвержденный будущий этап для этого сценария не выявлен'},'experiment':{'status':experiment}}
def none_docs(): return {'items':[],'refusalLetter':'Да, высокая вероятность','basis':'При назначении исключительно для животных и отсутствии электроники, лекарственного/кормового статуса или иных специальных свойств обязательное подтверждение соответствия по проверенным общим перечням предположительно отсутствует. Точный ТН ВЭД и ПП РФ № 2425 проверяются перед закупкой.'}

def detail(p,checked):
 prof=p['profile']; flags=[]; src=[]; result=p['result']; m=marking(); needs=['материал','конструкция/функция для точного 10-значного ТН ВЭД','подтверждение назначения исключительно для животных']
 if prof=='pet_simple':
  docs=none_docs(); flags=['none','refusal']; src=['pp-rf-2425']; reason='Низкая регуляторная нагрузка при подтвержденном назначении исключительно для животных и простом неэлектрическом исполнении.'
 elif prof=='pet_electric':
  docs={'items':[{'type':'declaration','label':'Обязательная оценка по ТР ТС 020/2011','status':'применимость зависит от технического исполнения'},{'type':'other','label':'Проверка ТР ТС 004/2011 и ТР ЕАЭС 037/2016','status':'зависит от напряжения и вида электроники'}],'refusalLetter':'Нет либо только после исключения электротехнических требований','basis':'Электрическое/электронное исполнение требует проверки технических регламентов; с 2026 года отдельные виды радиоэлектроники также вошли в Честный знак, поэтому нужен точный ТН ВЭД + ОКПД2 + наименование.'}; flags=['declaration']; src=['tr-ts-004','tr-ts-020','cz-radioelectronics-scope','cz-radioelectronics-stages']; m=marking('unknown','Для электроники требуется проверка точного ТН ВЭД, ОКПД2 и полного наименования по ПП РФ № 1954'); needs=['напряжение и источник питания','наличие радиомодуля','точный вид электроники','ТН ВЭД и ОКПД2'] ; reason='Электротехническое регулирование; возможна маркировка радиоэлектроники только при попадании в конкретный перечень.'
 elif prof=='pet_feed':
  docs={'items':[{'type':'other','label':'Документы/регистрация кормовой продукции','status':'точный набор определяется видом корма и составом'}],'refusalLetter':'Нет','basis':'Упакованные сухие корма и лакомства с ТН ВЭД 2309 и установленными ОКПД2 маркируются с 01.10.2024; влажные — с 01.03.2025. Для окончательного вывода нужен ОКПД2 из разрешительной документации.'}; flags=['other']; src=['cz-pet-feed-scope','cz-pet-feed-stages','pp-rf-674-2024']; m=marking('yes','Обязательна при ТН ВЭД 2309 и соответствующем ОКПД2: сухие корма/лакомства с 01.10.2024, влажные с 01.03.2025'); needs=['вид корма: сухой/влажный/лакомство','состав','ОКПД2 из разрешительной документации','точный код ТН ВЭД']; reason='Кормовая продукция имеет действующую обязательную маркировку и специальный регуляторный режим.'
 elif prof=='feed_additive':
  docs={'items':[{'type':'other','label':'Отдельная ветеринарная/кормовая проверка разрешительных требований','status':'зависит от состава и статуса кормовой добавки'}],'refusalLetter':'Нет','basis':'Кормовую добавку нельзя автоматически приравнивать к маркируемому корму: требуется точный ОКПД2, состав и статус продукции. Для кормовой добавки регуляторный вход остаётся сложным даже при отсутствии маркировки кормов.'}; flags=['other']; src=['cz-pet-feed-scope','pp-rf-674-2024']; m=marking('unknown','Не приравнивать автоматически к маркируемому корму; проверить ТН ВЭД 2309 и точный ОКПД2'); needs=['является ли продукт кормом или кормовой добавкой','ОКПД2','состав','назначение']; reason='Специальный кормовой/ветеринарный режим; маркировка зависит от точной идентификации.'
 elif prof=='vet_drug':
  docs={'items':[{'type':'other','label':'Действующее регистрационное удостоверение ветеринарного лекарственного препарата','status':'ключевой признак лекарственного препарата'}],'refusalLetter':'Нет','basis':'Для целей маркировки ветеринарных лекарственных препаратов учитываются коды перечня и наличие действующего регистрационного удостоверения. Перечень расширен с 01.03.2026.'}; flags=['other']; src=['cz-vet-drugs-scope','cz-vet-drugs-stages','pp-rf-675-2024']; m=marking('yes','Обязательна для ветеринарного лекарственного препарата при совпадении кодов перечня и наличии действующего РУ'); needs=['действующее регистрационное удостоверение','лекарственная форма','действующее вещество','ТН ВЭД и ОКПД2']; reason='Ветеринарный лекарственный препарат: действующая маркировка и регистрационный режим.'
 elif prof=='vet_parapharma':
  docs={'items':[],'refusalLetter':'Возможно после уточнения','basis':'Маркетинговое название «парафармацевтика» не определяет юридический режим. По составу и заявленным свойствам товар может оказаться ветеринарным лекарственным препаратом, кормовой добавкой либо обычным средством ухода.'}; flags=['unknown']; src=['cz-vet-drugs-scope','cz-pet-feed-scope','pp-rf-2425']; m=marking('unknown','Зависит от того, является ли товар зарегистрированным ветпрепаратом, кормом/добавкой или обычным средством ухода'); needs=['состав','лечебные/профилактические заявления','наличие РУ ветпрепарата','кормовое назначение']; reason='Требуется юридическая идентификация по составу и заявлениям.'
 elif prof=='pet_chemical':
  docs={'items':[],'refusalLetter':'Возможно после уточнения','basis':'Для средства ухода за животными необходимы состав и заявленные свойства. Лечебные/противопаразитарные заявления могут перевести товар в режим ветеринарного препарата; обычное средство ухода может иметь иной режим.'}; flags=['unknown']; src=['cz-vet-drugs-scope','pp-rf-2425']; m=marking('unknown','Проверить после определения состава, заявленного действия, ТН ВЭД и ОКПД2'); needs=['полный состав','лечебные/профилактические/противопаразитарные заявления','форма применения','наличие регистрации ветпрепарата']; reason='Состав и заявления способны принципиально изменить документы и маркировку.'
 elif prof=='vet_consumable':
  docs={'items':[],'refusalLetter':'Возможно после уточнения','basis':'Ветеринарное назначение само по себе не позволяет определить обязательный документ: необходимо установить, является ли товар обычным аксессуаром/расходником, электронным устройством или регулируемым ветеринарным/диагностическим изделием.'}; flags=['unknown']; src=['pp-rf-2425']; m=marking('unknown','Для простых расходников маркировка обычно не выявляется, но электронные/специальные изделия требуют отдельной проверки'); needs=['точная функция','материал','электронное исполнение','регистрационное/диагностическое назначение']; reason='Нужна дополнительная идентификация ветеринарного расходника.'
 else: # live_bio
  docs={'items':[{'type':'other','label':'Специальные ветеринарные/фитосанитарные требования','status':'зависят от вида живого объекта и происхождения'}],'refusalLetter':'Нет','basis':'Живые растения, икра, насекомые и другие биологические объекты требуют отдельной проверки ветеринарных, карантинных или фитосанитарных правил. Обычный режим отказного письма не является достаточным screening.'}; flags=['other']; src=[]; m=marking('no','Товар не относится к выявленным товарным группам Честного знака; основные риски находятся вне системы маркировки'); needs=['точный биологический вид','живой/неживой товар','происхождение','условия ввоза/оборота']; reason='Специальный биологический/ветеринарный контроль делает вход сложным независимо от ЧЗ.'
 return {'normalizedName':p['name'],'marking':m,'tnved':{'candidates':[{'code':p['tn'],'confidence':'низкий' if '/' in p['tn'] else 'средний','description':'Предварительная группа; точный 10-значный код определяется после характеристик.'}],'needsClarification':needs},'documents':docs,'sourceIds':src,'lastChecked':checked,'screeningReason':reason},flags

def sc(code,items,result,mark='no'):
 return {'tnvedCandidates':[{'code':code}],'documents':{'status':'none' if result=='green' else 'mandatory' if result=='red' else 'check','items':items},'marking':{'current':{'status':mark},'future':{'status':'no'},'experiment':{'status':'no'}},'result':result}
def rule(p):
 prof=p['profile']; code=p['tn']
 if prof=='pet_simple': return {'questionIds':['animalOnly','electric'], 'scenarios':[{'label':'Простое неэлектрическое изделие исключительно для животных','when':{'animalOnly':{'eq':'yes'},'electric':{'eq':'no'}},'output':sc(code,[],'green','no')},{'label':'Есть электроника','when':{'electric':{'eq':'yes'}},'output':sc(code,[{'label':'Проверка ТР ТС 004/2011, 020/2011, ТР ЕАЭС 037/2016 и ЧЗ радиоэлектроники'}],'red','unknown')},{'label':'Не подтверждено назначение исключительно для животных','when':{'animalOnly':{'eq':'no'}},'output':sc(code,[{'label':'Требуется повторная классификация по фактическому назначению'}],'yellow','unknown')}]}
 if prof=='pet_electric': return {'questionIds':['mainsPowered','batteryPowered','ratedVoltage','radioWireless'], 'scenarios':[{'label':'Электрическое/электронное изделие для животных','when':{},'output':sc(code,[{'label':'Обязательная проверка ТР ТС 004/2011, 020/2011, ТР ЕАЭС 037/2016; ЧЗ по точному ТН ВЭД/ОКПД2'}],'red','unknown')}]}
 if prof=='pet_feed': return {'questionIds':['petNutritionType'], 'scenarios':[{'label':'Сухой корм','when':{'petNutritionType':{'eq':'Сухой корм'}},'output':sc('2309',[{'label':'Маркировка кормов действует с 01.10.2024; проверить ОКПД2'}],'red','yes')},{'label':'Лакомство','when':{'petNutritionType':{'eq':'Лакомство'}},'output':sc('2309',[{'label':'Маркировка кормов действует с 01.10.2024; проверить ОКПД2'}],'red','yes')},{'label':'Влажный корм','when':{'petNutritionType':{'eq':'Влажный корм'}},'output':sc('2309',[{'label':'Маркировка кормов действует с 01.03.2025; проверить ОКПД2'}],'red','yes')},{'label':'Фактически кормовая добавка','when':{'petNutritionType':{'eq':'Кормовая добавка'}},'output':sc('2309',[{'label':'Не приравнивать автоматически к маркируемому корму; нужен ОКПД2 и статус добавки'}],'red','unknown')}]}
 if prof=='feed_additive': return {'questionIds':['petNutritionType'], 'scenarios':[{'label':'Подтвержденная кормовая добавка','when':{'petNutritionType':{'eq':'Кормовая добавка'}},'output':sc('2309',[{'label':'Специальная проверка разрешительных требований; маркировка кормов зависит от ОКПД2'}],'red','unknown')},{'label':'Фактически сухой/влажный корм или лакомство','when':{'petNutritionType':{'in':['Сухой корм','Влажный корм','Лакомство']}},'output':sc('2309',[{'label':'Проверить обязательную маркировку кормов по ОКПД2'}],'red','yes')}]}
 if prof=='vet_drug': return {'questionIds':['vetDrugRegistered'], 'scenarios':[{'label':'Есть действующее РУ ветеринарного препарата','when':{'vetDrugRegistered':{'eq':'yes'}},'output':sc(code,[{'label':'Ветеринарное РУ; проверить код в действующем перечне маркировки'}],'red','yes')},{'label':'РУ отсутствует','when':{'vetDrugRegistered':{'eq':'no'}},'output':sc(code,[{'label':'Нельзя считать товар легально идентифицированным ветеринарным лекарственным препаратом; требуется проверка фактического статуса'}],'red','unknown')}]}
 if prof in ('vet_parapharma','pet_chemical'): return {'questionIds':['veterinaryMedicinalClaim','vetDrugRegistered'], 'scenarios':[{'label':'Есть лечебное/профилактическое ветеринарное действие и РУ','when':{'veterinaryMedicinalClaim':{'eq':'yes'},'vetDrugRegistered':{'eq':'yes'}},'output':sc(code,[{'label':'Режим ветеринарного лекарственного препарата; проверить ЧЗ по кодам перечня'}],'red','yes')},{'label':'Обычное средство ухода без лечебных заявлений','when':{'veterinaryMedicinalClaim':{'eq':'no'},'vetDrugRegistered':{'eq':'no'}},'output':sc(code,[{'label':'Требуется проверка состава и точного ТН ВЭД; возможен простой сценарий'}],'yellow','unknown')}]}
 if prof=='vet_consumable': return {'questionIds':['electric','veterinaryMedicinalClaim'], 'scenarios':[{'label':'Простой неэлектрический расходник без лекарственного действия','when':{'electric':{'eq':'no'},'veterinaryMedicinalClaim':{'eq':'no'}},'output':sc(code,[{'label':'Проверить точный код по ПП РФ № 2425; возможен отказной сценарий'}],'yellow','no')},{'label':'Электронное/специальное изделие','when':{'electric':{'eq':'yes'}},'output':sc(code,[{'label':'Дополнительная техническая и ветеринарная проверка'}],'red','unknown')}]}
 if prof=='live_bio': return {'questionIds':['liveBiologicalObject'], 'scenarios':[{'label':'Живой биологический объект подтвержден','when':{'liveBiologicalObject':{'eq':'yes'}},'output':sc(code,[{'label':'Специальные ветеринарные/фитосанитарные требования'}],'red','no')},{'label':'Фактически неживой аксессуар/субстрат','when':{'liveBiologicalObject':{'eq':'no'}},'output':sc(code,[{'label':'Требуется повторная классификация как обычного товара'}],'yellow','unknown')}]}
 return {'questionIds':[],'scenarios':[]}

def main():
 patch_registry(); b=load(SRC,{}); products=b.get('products',[]); checked=b.get('checkedAt','2026-08-27'); summary=load(DATA/'compliance-summary.json',{}); dfs={}; rfs={}
 for p in products:
  sh=shard(p['id']); dfs.setdefault(sh,load(DATA/'compliance/details'/sh,{})); rfs.setdefault(sh,load(DATA/'rules/products'/sh,{})); d,flags=detail(p,checked); mark=d['marking']['current']['status']; summary[str(p['id'])]={'result':p['result'],'markingCurrent':mark,'markingFuture':'no','experiment':'no','documentFlags':flags,'tnvedCodes':codes(p['tn']),'lastChecked':checked}; dfs[sh][str(p['id'])]=d; rfs[sh][str(p['id'])]=rule(p)
 write(DATA/'compliance-summary.json',summary)
 for n,o in dfs.items(): write(DATA/'compliance/details'/n,o)
 for n,o in rfs.items(): write(DATA/'rules/products'/n,o)
 meta=load(DATA/'meta.json',{}); stats={'green':0,'yellow':0,'red':0}
 for s in summary.values():
  if s.get('result') in stats: stats[s['result']]+=1
 meta['complianceStatus']='partial'; meta['checkedProducts']=len(summary); meta['screeningStats']=stats; meta['lastComplianceBuild']=checked; write(DATA/'meta.json',meta)
 print(f"Merged {len(products)} pet products; total {len(summary)}; stats {stats}")
if __name__=='__main__': main()
